name: listing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.1
  flutter_animate: ^4.2.0+1
  google_fonts: ^6.1.0
  top_modal_sheet: ^2.0.1
  getwidget: ^4.0.0
  flutter_spinkit: ^5.2.0
  logger: ^2.0.2+1
  get_storage: ^2.1.1
  lottie: ^2.7.0
  gap: ^3.0.1
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - lib/graphics/
  - lib/graphics/logo/
  - lib/graphics/png/
  - lib/graphics/lottie/


