name: listing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.1
  flutter_animate: ^4.2.0+1
  google_fonts: ^6.1.0
  top_modal_sheet: ^2.0.1
  getwidget: ^4.0.0
  flutter_spinkit: ^5.2.0
  logger: ^2.0.2+1
  get_storage: ^2.1.1
  lottie: ^2.7.0
  gap: ^3.0.1
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - lib/graphics/
  - lib/graphics/logo/
  - lib/graphics/png/
  - lib/graphics/lottie/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/graphics/logo/main.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/graphics/logo/main.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "lib/graphics/logo/main.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/graphics/logo/main.png"